package Throw;

public class ThrowException {

	public static void main(String[] args){
		// TODO 자동 생성된 메소드 스텁
//		try {
//			throw new Exception("강제로 예외발생");
//		}catch (Exception e) {
//			// TODO: handle exception
//			e.printStackTrace();
//			System.out.println(e.getMessage());
//		}
		try {
			method1();
		}catch (Exception e) {
				// TODO: handle exception
			System.out.println(e.getMessage());
			}
		
	}
	public static void method1() throws Exception {
		method2();
	}
	public static void method2() throws Exception {
		throw new Exception("나는 문제가 있다");
	}
	

}
